import google.generativeai as genai
import PyPDF2
import docx
import json
import pandas as pd
from typing import List, Dict

def extract_text_from_pdf(file) -> str:
    """Extracts text from a PDF file."""
    pdf_reader = PyPDF2.PdfReader(file)
    text = ""
    for page in pdf_reader.pages:
        text += page.extract_text()
    return text

def extract_text_from_docx(file) -> str:
    """Extracts text from a DOCX file."""
    doc = docx.Document(file)
    text = ""
    for paragraph in doc.paragraphs:
        text += paragraph.text + "\n"
    return text

def extract_text(file) -> str:
    """Extracts text based on file extension."""
    if file.name.endswith('.pdf'):
        return extract_text_from_pdf(file)
    elif file.name.endswith('.docx'):
        return extract_text_from_docx(file)
    else:
        return ""

def score_resumes(resumes: List[Dict], job_description: str, api_key: str) -> List[Dict]:
    """
    Scores resumes against the job description using Gemini.
    
    Args:
        resumes: List of dicts with 'filename' and 'text'.
        job_description: The job description text.
        api_key: Google Gemini API Key.
        
    Returns:
        List of dicts with scoring details.
    """
    if not api_key:
        return []

    genai.configure(api_key=api_key)
    model = genai.GenerativeModel('gemini-1.5-flash')

    results = []
    
    # Process each resume (in a real app, we might batch this or use async)
    for resume in resumes:
        prompt = f"""
        You are an expert HR AI assistant. Your task is to evaluate a resume against a job description.
        
        Job Description:
        {job_description}
        
        Resume Content:
        {resume['text']}
        
        Analyze the resume and provide the following in JSON format:
        1. "score": A score from 0 to 100 based on the match.
        2. "matching_skills": Top 5 matching skills found in the resume.
        3. "missing_skills": Key skills from the JD missing in the resume.
        4. "experience_years": Estimated years of relevant experience.
        5. "summary": A 1-2 sentence summary of the candidate's fit.
        6. "recommendation": "Strong Hire", "Hire", "Maybe", "Reject".
        
        Return ONLY valid JSON.
        """
        
        try:
            response = model.generate_content(prompt)
            # Simple cleanup to ensure JSON parsing if the model adds markdown blocks
            text_response = response.text.replace("```json", "").replace("```", "").strip()
            analysis = json.loads(text_response)
            
            analysis['filename'] = resume['filename']
            results.append(analysis)
        except Exception as e:
            print(f"Error processing {resume['filename']}: {e}")
            results.append({
                "filename": resume['filename'],
                "score": 0,
                "summary": f"Error processing resume: {str(e)}",
                "recommendation": "Error"
            })
            
    # Sort by score descending
    results.sort(key=lambda x: x.get('score', 0), reverse=True)
    return results

def generate_job_description(role: str, api_key: str) -> str:
    """
    Generates a job description using Gemini.
    
    Args:
        role: The job role or title.
        api_key: Google Gemini API Key.
        
    Returns:
        Generated job description text.
    """
    if not api_key:
        return "Error: API Key is missing."
        
    try:
        genai.configure(api_key=api_key)
        model = genai.GenerativeModel('gemini-1.5-flash')
        
        prompt = f"""
        Create a professional and detailed job description for the role of: {role}.
        Include the following sections:
        - Job Title
        - About the Role
        - Key Responsibilities
        - Required Qualifications
        - Preferred Qualifications
        
        Keep it professional and ready to use.
        """
        
        response = model.generate_content(prompt)
        return response.text
    except Exception as e:
        return f"Error generating job description: {str(e)}"

def mock_generate_job_description(role: str) -> str:
    """Generates a mock job description."""
    return f"""
    **Job Title:** {role} (Demo)
    
    **About the Role:**
    This is a demo job description for a {role}. In a real scenario, this would be generated by Google Gemini AI based on your input.
    
    **Key Responsibilities:**
    - Responsibility 1 for {role}
    - Responsibility 2 for {role}
    - Responsibility 3 for {role}
    
    **Required Qualifications:**
    - Qualification 1
    - Qualification 2
    """

def mock_score_resumes(resumes: List[Dict], job_description: str) -> List[Dict]:
    """Generates mock scores for resumes."""
    import random
    results = []
    for resume in resumes:
        score = random.randint(60, 95)
        results.append({
            "filename": resume['filename'],
            "score": score,
            "matching_skills": ["Python", "Streamlit", "AI", "Communication"],
            "missing_skills": ["Docker", "Kubernetes"],
            "experience_years": "3-5 years",
            "summary": f"This is a demo analysis for {resume['filename']}. The candidate appears to be a good fit with a score of {score}.",
            "recommendation": "Strong Hire" if score > 80 else "Hire"
        })
    results.sort(key=lambda x: x.get('score', 0), reverse=True)
    return results
